version: '2'
services:
    sociallinks-app:
        image: sociallinks
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sociallinks-postgresql:5432/sociallinks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sociallinks-postgresql:
        extends:
            file: postgresql.yml
            service: sociallinks-postgresql
